/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateSlotArgs = IDL.Record({
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
});
export const SlotId = IDL.Nat;
export const TimeSlotView = IDL.Record({
  'id' : SlotId,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const UpdateSlotArgs = IDL.Record({
  'id' : SlotId,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSlot' : IDL.Func([CreateSlotArgs], [TimeSlotView], []),
  'deleteSlot' : IDL.Func([SlotId], [IDL.Bool], []),
  'listSlots' : IDL.Func([], [IDL.Vec(TimeSlotView)], ['query']),
  'toggleSlotComplete' : IDL.Func([SlotId], [IDL.Opt(TimeSlotView)], []),
  'updateSlot' : IDL.Func([UpdateSlotArgs], [IDL.Opt(TimeSlotView)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateSlotArgs = IDL.Record({
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
  });
  const SlotId = IDL.Nat;
  const TimeSlotView = IDL.Record({
    'id' : SlotId,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  const UpdateSlotArgs = IDL.Record({
    'id' : SlotId,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'createSlot' : IDL.Func([CreateSlotArgs], [TimeSlotView], []),
    'deleteSlot' : IDL.Func([SlotId], [IDL.Bool], []),
    'listSlots' : IDL.Func([], [IDL.Vec(TimeSlotView)], ['query']),
    'toggleSlotComplete' : IDL.Func([SlotId], [IDL.Opt(TimeSlotView)], []),
    'updateSlot' : IDL.Func([UpdateSlotArgs], [IDL.Opt(TimeSlotView)], []),
  });
};

export const init = ({ IDL }) => { return []; };